services:
  - type: web
    name: replate-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
